version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run:
          name: Checkout submodules
          command: |
            git submodule update --init --recursive
            # Write out the status for debugging purposes. Are we checked out at tags?
            git submodule status --recursive
       - run: dotnet build
